### ISSUE TITLE
EmpyrionChatAutoTranslate - Errors in dedicated server logs every time a user sends a message 

### ISSUE THREAD

**Issue by RedScourge** [GitHub-TC/EmpyrionModPackage#1]
Every time someone sends a message in game, an error like the following appears in the dedicated server log - possible change to the EAH discord integration?

```
10-03:02:43.221 20_02 -LOG- {EPM} Timelog: Send to Dedi: 6/min
10-03:02:43.221 20_02 -LOG- {EPM} Timelog: Received from Dedi: 78/min
10-03:02:52.824 20_02 -LOG- INFO: Uptime=04h59m 60.058 2390 heap=1609MB fps=40.0 players= 2 pfs=r0/i4/a1 ticks=29830239 nwqueue=Net:0/2
10-03:03:20.874 20_03 -LOG- CHAT Player/Faction from 6092/Faction.100 to -1/Faction.100 (-): 'nope'
10-03:03:20.874 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost: **HandleEmpyrionChatAutoTranslate Translate 5: playerId:6092 recipientEntityId:-1 recipientFactionId:100 msg:nope
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost: HandleGameEvent: CmdId:Event_ChatMessage seqNr:0 data:Eleon.Modding.ChatInfo => System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at EmpyrionChatDiscordBridge.ChatDiscordBridge.<ChatDiscordBridge_Event_ChatMessage>d__29.MoveNext()
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost: --- End of stack trace from previous location where exception was thrown ---
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at EmpyrionChatDiscordBridge.ChatDiscordBridge.<Initialize>b__25_1(ChatInfo msg)
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    --- End of inner exception stack trace ---
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.Delegate.DynamicInvokeImpl(Object[] args)
10-03:03:20.876 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at System.Delegate.DynamicInvoke(Object[] args)
10-03:03:20.877 20_03 -LOG- {:EmpyrionModClient} EmpyrionModHost:    at EmpyrionNetAPIAccess.Broker.HandleGameEvent(CmdId eventId, UInt16 seqNr, Object data)
10-03:03:43.221 20_03 -LOG- {EPM} Timelog: Send to Dedi: 4/min
10-03:03:43.221 20_03 -LOG- {EPM} Timelog: Received from Dedi: 75/min
```

**Comment by GitHub-TC** [comment]
Whenyou dont need/configure the EmpyrionChatDiscordBridge you have to disable the mod.
The HandleEmpyrionChatAutoTranslate is not responsible for this message
